package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Actie generated by hbm2java
 * Actie pojo klasse, houdt informatie bij over de lading en de opdracht.
 */

public class Actie  implements java.io.Serializable {

    
     private int actieid;
     private int opdrachtid;
     private Boolean actieklaar;
     private Date starttijd;
     private Date eindtijd;
     private String soortActie;
     private String lading;
     private String vrijveld;
     private String adres;

    public Actie() {
    }
    
    public Actie(int opdrachtid, Boolean actieklaar, Date starttijd, Date eindtijd, String soortactie, String lading, String vrijveld, String adres) {
        this.opdrachtid = opdrachtid;
        this.actieklaar = actieklaar;
        this.starttijd = starttijd;
        this.eindtijd = eindtijd;
        this.soortActie = soortactie;
        this.lading = lading;
        this.vrijveld = vrijveld;
        this.adres = adres;
    }
    
    public Actie(int actieid, int opdrachtid, Boolean actieklaar,Date starttijd, Date eindtijd, String soortactie, String lading, String vrijveld, String adres) {
        this.actieid = actieid;
        this.opdrachtid = opdrachtid;
        this.actieklaar = actieklaar;
        this.starttijd = starttijd;
        this.eindtijd = eindtijd;
        this.soortActie = soortactie;
        this.lading = lading;
        this.vrijveld = vrijveld;
        this.adres = adres;
    }

    public String getAdres() {
        return adres;
    }

    public void setAdres(String adres) {
        this.adres = adres;
    }
   
    public int getActieid() {
        return this.actieid;
    }

    public Date getStarttijd() {
        return this.starttijd;
    }

    public void setStarttijd(Date starttijd) {
        this.starttijd = starttijd;
    }

    public Date getEindtijd() {
        return this.eindtijd;
    }

    public void setEindtijd(Date eindtijd) {
        this.eindtijd = eindtijd;
    }

    public String getSoortActie() {
        return soortActie;
    }

    public void setSoortActie(String soortActie) {
        this.soortActie = soortActie;
    }
    
    public void setActieid(int actieid) {
        this.actieid = actieid;
    }
    public int getOpdrachtid() {
        return this.opdrachtid;
    }
    
    public void setOpdrachtid(int opdrachtid) {
        this.opdrachtid = opdrachtid;
    }
    public Boolean getActieklaar() {
        return this.actieklaar;
    }
    
    public void setActieklaar(Boolean actieklaar) {
        this.actieklaar = actieklaar;
    }
    public String getLading() {
        return this.lading;
    }
    
    public void setLading(String lading) {
        this.lading = lading;
    }
    public String getVrijveld() {
        return this.vrijveld;
    }
    
    public void setVrijveld(String vrijveld) {
        this.vrijveld = vrijveld;
    }




}


