package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA



/**
 * Facturatie generated by hbm2java
 * Facturatie gegevens.
 */
public class Facturatie  implements java.io.Serializable {


     private int facturatieid;
     private int klant;
     private Double korting;
     private Double prijsgegeven;

    public Facturatie() {
    }

    public Facturatie(int facturatieid, int klant,double korting, Double prijsgegeven) {
       this.facturatieid = facturatieid;
       this.klant = klant;
       this.korting = korting;
       this.prijsgegeven = prijsgegeven;
    }
   
    public int getFacturatieid() {
        return this.facturatieid;
    }
    
    public void setFacturatieid(int facturatieid) {
        this.facturatieid = facturatieid;
    }
    public int getKlant() {
        return this.klant;
    }
    
    public void setKlant(int klant) {
        this.klant = klant;
    }
    public Double getPrijsgegeven() {
        return this.prijsgegeven;
    }
    
    public void setPrijsgegeven(Double prijsgegeven) {
        this.prijsgegeven = prijsgegeven;
    }

    public Double getKorting() {
        return korting;
    }

    public void setKorting(Double korting) {
        this.korting = korting;
    }
    
}


