package be.pxl.publictms.pojo;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA

/**
 * Klant generated by hbm2java
 * Klant gegevens
 */
public class Klant  implements java.io.Serializable {


     private int klantid;
     private int transportadresid;
     private String naam;
     private String voornaam;
     private String bedrijf;
     private String website;
     private String betalingscondities;
     private String munt;
     private String btwregime;
     private String btwnummer;
     private String ondernemingsnummer;
     private String iban;
     private String bic;
     
    public Klant() {
    }
    
    public Klant(int transportadresid, String naam, String voornaam, String bedrijf, String website, String betalingscondities, String munt, String btwregime, String btwnummer, String ondernemingsnummer, String iban, String bic) {
        this.transportadresid = transportadresid;
        this.naam = naam;
        this.voornaam = voornaam;
        this.bedrijf = bedrijf;
        this.website = website;
        this.betalingscondities = betalingscondities;
        this.munt = munt;
        this.btwregime = btwregime;
        this.btwnummer = btwnummer;
        this.ondernemingsnummer = ondernemingsnummer;
        this.iban = iban;
        this.bic = bic;
    }

    public Klant(int klantid, int transportadresid, String naam, String voornaam, String bedrijf, String website, String betalingscondities, String munt, String btwregime, String btwnummer, String ondernemingsnummer, String iban, String bic) {
        this.klantid = klantid;
        this.transportadresid = transportadresid;
        this.naam = naam;
        this.voornaam = voornaam;
        this.bedrijf = bedrijf;
        this.website = website;
        this.betalingscondities = betalingscondities;
        this.munt = munt;
        this.btwregime = btwregime;
        this.btwnummer = btwnummer;
        this.ondernemingsnummer = ondernemingsnummer;
        this.iban = iban;
        this.bic = bic;
    }

    public String getBetalingscondities() {
        return betalingscondities;
    }

    public void setBetalingscondities(String betalingscondities) {
        this.betalingscondities = betalingscondities;
    }

    public String getMunt() {
        return munt;
    }

    public void setMunt(String munt) {
        this.munt = munt;
    }

    public String getBtwregime() {
        return btwregime;
    }

    public void setBtwregime(String btwregime) {
        this.btwregime = btwregime;
    }

    public String getBtwnummer() {
        return btwnummer;
    }

    public void setBtwnummer(String btwnummer) {
        this.btwnummer = btwnummer;
    }

    public String getOndernemingsnummer() {
        return ondernemingsnummer;
    }

    public void setOndernemingsnummer(String ondernemingsnummer) {
        this.ondernemingsnummer = ondernemingsnummer;
    }

    public String getIban() {
        return iban;
    }

    public void setIban(String iban) {
        this.iban = iban;
    }

    public String getBic() {
        return bic;
    }

    public void setBic(String bic) {
        this.bic = bic;
    }
 
    public int getKlantid() {
        return this.klantid;
    }
    
    public void setKlantid(int klantid) {
        this.klantid = klantid;
    }
    public int getTransportadresid() {
        return this.transportadresid;
    }
    
    public void setTransportadresid(int transportadresid) {
        this.transportadresid = transportadresid;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getVoornaam() {
        return this.voornaam;
    }
    
    public void setVoornaam(String voornaam) {
        this.voornaam = voornaam;
    }
    public String getBedrijf() {
        return this.bedrijf;
    }
    
    public void setBedrijf(String bedrijf) {
        this.bedrijf = bedrijf;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
}


