package be.pxl.publictms.view;
// Generated 19-dec-2013 20:16:01 by Hibernate Tools 3.2.1.GA


/**
 * Bericht generated by hbm2java
 * Beschikt datum, body, ontvanger en verzender, datum.
 */
public class BerichtView{
    private Object berichtid;
    private Object berichttitel;
    private Object bericht;
    private Object datum;
    private Object verzender;
    private Object ontvangerid;
    private Object verstuurderid;
    private Object gelezen;

    public BerichtView(){
        
    }
    
    public BerichtView(Object berichtid, Object berichttitel, Object bericht, Object datum, Object verzender, Object ontvangerid, Object verstuurderid, Object gelezen) {
        this.berichtid = berichtid;
        this.berichttitel = berichttitel;
        this.bericht = bericht;
        this.datum = datum;
        this.verzender = verzender;
        this.ontvangerid = ontvangerid;
        this.verstuurderid = verstuurderid;
        this.gelezen = gelezen;
    }

    public Object getBerichtid() {
        return berichtid;
    }

    public void setBerichtid(Object berichtid) {
        this.berichtid = berichtid;
    }

    public Object getBerichttitel() {
        return berichttitel;
    }

    public void setBerichttitel(Object berichttitel) {
        this.berichttitel = berichttitel;
    }

    public Object getBericht() {
        return bericht;
    }

    public void setBericht(Object bericht) {
        this.bericht = bericht;
    }

    public Object getDatum() {
        return datum;
    }

    public void setDatum(Object datum) {
        this.datum = datum;
    }

    public Object getVerzender() {
        return verzender;
    }

    public void setVerzender(Object verzender) {
        this.verzender = verzender;
    }

    public Object getOntvangerid() {
        return ontvangerid;
    }

    public void setOntvangerid(Object ontvangerid) {
        this.ontvangerid = ontvangerid;
    }

    public Object getGelezen() {
        return gelezen;
    }

    public void setGelezen(Object gelezen) {
        this.gelezen = gelezen;
    }   

    public Object getVerstuurderid() {
        return verstuurderid;
    }

    public void setVerstuurderid(Object verstuurderid) {
        this.verstuurderid = verstuurderid;
    }
    
}


